-- MySQL Script generated by MySQL Workbench
-- Tue Nov  8 19:06:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema teacherapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema teacherapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teacherapp` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `teacherapp` ;

-- -----------------------------------------------------
-- Table `teacherapp`.`branches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teacherapp`.`branches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `teacherapp`.`provinces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teacherapp`.`provinces` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `teacherapp`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teacherapp`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_city_province_idx` (`province_id` ASC),
  CONSTRAINT `FK_city_province`
    FOREIGN KEY (`province_id`)
    REFERENCES `teacherapp`.`provinces` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `teacherapp`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teacherapp`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `teacherapp`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teacherapp`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `creation_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(60) NOT NULL,
  `surname` VARCHAR(80) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `FK_User_role_idx` (`role_id` ASC),
  CONSTRAINT `FK_User_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `teacherapp`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `teacherapp`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teacherapp`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` TINYINT NULL DEFAULT '1',
  `phone` VARCHAR(12) NULL DEFAULT NULL,
  `avatar` VARCHAR(150) NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_User_Student_idx` (`user_id` ASC),
  CONSTRAINT `FK_User_Student`
    FOREIGN KEY (`user_id`)
    REFERENCES `teacherapp`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `teacherapp`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teacherapp`.`location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `city_id` INT NOT NULL,
  `province_id` INT NOT NULL,
  `address` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Location_City_idx` (`city_id` ASC),
  INDEX `FK_Location_Province_idx` (`province_id` ASC),
  CONSTRAINT `FK_Location_City`
    FOREIGN KEY (`city_id`)
    REFERENCES `teacherapp`.`cities` (`id`),
  CONSTRAINT `FK_Location_Province`
    FOREIGN KEY (`province_id`)
    REFERENCES `teacherapp`.`provinces` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `teacherapp`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teacherapp`.`teachers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(12) NULL DEFAULT NULL,
  `branch_id` INT NOT NULL,
  `price_hour` DOUBLE UNSIGNED NOT NULL,
  `experience` INT UNSIGNED NULL DEFAULT NULL,
  `validated` TINYINT UNSIGNED NULL DEFAULT '0',
  `location_id` INT NOT NULL,
  `avatar` VARCHAR(120) NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  `subjects` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Location_idx` (`location_id` ASC),
  INDEX `FK_Branch_idx` (`branch_id` ASC),
  INDEX `FK_User_teacher_idx` (`user_id` ASC),
  CONSTRAINT `FK_Branch`
    FOREIGN KEY (`branch_id`)
    REFERENCES `teacherapp`.`branches` (`id`),
  CONSTRAINT `FK_Location`
    FOREIGN KEY (`location_id`)
    REFERENCES `teacherapp`.`location` (`id`),
  CONSTRAINT `FK_User_teacher`
    FOREIGN KEY (`user_id`)
    REFERENCES `teacherapp`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `teacherapp`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teacherapp`.`classes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `class_datetime` DATETIME NULL DEFAULT NULL,
  `teacher_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_class_teacher` (`teacher_id` ASC, `class_datetime` ASC),
  INDEX `FK_Class_student_idx` (`student_id` ASC),
  INDEX `FK_Class_teacher_idx` (`teacher_id` ASC),
  CONSTRAINT `FK_Class_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `teacherapp`.`students` (`id`),
  CONSTRAINT `FK_Class_teacher`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `teacherapp`.`teachers` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `teacherapp`.`errors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teacherapp`.`errors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(8) NOT NULL,
  `message` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `teacherapp`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teacherapp`.`ratings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rating` INT NOT NULL,
  `comment` LONGTEXT NULL DEFAULT NULL,
  `teacher_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Rating_Teacher_idx` (`teacher_id` ASC),
  INDEX `FK_Rating_Student_idx` (`student_id` ASC),
  CONSTRAINT `FK_Rating_Student`
    FOREIGN KEY (`student_id`)
    REFERENCES `teacherapp`.`students` (`id`),
  CONSTRAINT `FK_Rating_Teacher`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `teacherapp`.`teachers` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
