POST http://localhost:3000/users/signin
Content-Type: application/json

{
    "email": "felix@gmail.com",
    "password": "123"
}

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "gdobrowolski16@unesco.org",
    "password": "Spain",
    "role_id": 1
}